### PR TITLE
add all query settings to all query panels

### PR DESCRIPTION
**Pull request by butlerx**
## What does this do?

ensures all query panels have the same default query settings

## Why is it a good idea?

allows settings to be copied and defaults reused

### CODE REVIEW

**Comment by dholbach** [comment]
Just a quick PSA from me: 
1. we're hanging out in [#grafanalib on Slack](https://weave-community.slack.com/archives/grafanalib)
1. we're planning a contributors meeting soon: here's the [link to the doodle](https://doodle.com/poll/hgsp9wmuff7m9bi7) to find a good time - be sure to pick your timezone before submitting ([preliminary agenda](https://docs.google.com/document/d/1JxrSszyPHYhNbJDWYZehRKv6AO4U-zIBhuNmYQVOIHo/edit))

We'd love to see you there.

**Comment by matthewmrichter** [comment]
It's harder to review this change with the reformatting of so many strings from single to double quotes. I'm also unsure what the best practice code style would be for this. But perhaps you could submit the quotation marks changes separately from the query settings change.

**Comment by dholbach** [comment]
Actual diff is https://gist.github.com/dholbach/ca4f779c8d747ead757b2dc07fbd16ac

**Comment by dholbach** [comment]
Thanks again for your PR. It's been a while since we reviewed this. We'll close the PR for now as grafanalib mainline has already moved on a bit. Please reopen the PR if you want to move this work forward again. We're also happy to chat with you [on Slack](https://weave-community.slack.com/archives/C9C9K6T4P) if you have any questions.

**Pull request closed without merging**
