### PR TITLE
Add 'diff', 'percent_diff' and 'count_non_null' as RTYPE

### PR DESCRIPTION
**Pull request by vicmarbev**
## What does this do?

Added 'diff', 'percent_diff' and 'count_non_null' as RTYPE for AlertConditions

## Why is it a good idea?

It allows grafanalib to use those reducers in AlertConditions

## Context

These three RTYPEs were missing in core.py

### CODE REVIEW

**Comment by vicmarbev** [comment]
Done!

**Comment by bboreham** [comment]
I think something went wrong with your rebase - there are now 13 commits in this PR.

**Comment by vicmarbev** [comment]
I think now it is correct

**Comment by bboreham** [comment]
Thanks!

**Pull request merged**
