### PR TITLE
Add bar guage panel

### PR DESCRIPTION
**Pull request by butlerx**
## What does this do?

Adds the ability to create bar guage panels in grafana 6 and up

## Why is it a good idea?

ability to take full advantage of grafana's built-in panels

### CODE REVIEW

**Comment by bboreham** [comment]
Is this a replacement for #178 ?

**Comment by butlerx** [comment]
no gauges and bar gauges are different panels.

**Comment by dholbach** [comment]
Mh. Isn't there some code duplicate between #178 and this one?

**Comment by matthewmrichter** [comment]
There's a merge conflict going on here, Github thingk that these two classes (The guagepanel one from #178 and the barguagepanel from #179) are the same. I will attempt to manually resolve it.

**Comment by matthewmrichter** [comment]
I figured out what I'm doing and got this merged in #206.

**Pull request merged**
