### PR TITLE
Adding InfluxDBTarget to support influxdb datasources

### PR DESCRIPTION
**Pull request by qmnonic**
## What does this do?
Minimal updates to support an influxdb datasource.

## Why is it a good idea?
Lots of people out there using influxdb datasources, including myself.

## Context
Current implementation doesn't allow influxdb based datasources.

Example -
```
  return G.Graph(
    span=3,
    title=f"example graf",
    lines=True,
    targets=[
      InfluxDBTarget(
        query=f'SELECT last("count") FROM "some_measurement" WHERE $timeFilter GROUP BY time($__interval) fill(null)',
        refId='A',
        alias='$tag_whatever_you_want'
      )
    ],
    id=graph_id,
    fill=2,
    lineWidth=1,
    dataSource='specify_datasource',
    legend=Legend(show=False),
  )
```

## Questions
Not a full implementation, focuses on minimal functionality - raw queries, thus can be expanded later.  Also doesn't address influxdb based alerts, which I'll likely create a PR for later.

### CODE REVIEW

**Comment by qmnonic** [comment]
Not sure how my PR caused a test failure, it's a completely new class.

**Comment by larsderidder** [comment]
+1 on this. I think it would also be good to extend the Target class with all possible fields, and still this class would be a good idea to make it more focused.

There's still some activity in this repo so perhaps @bboreham wouldn't mind to weigh in. I've copied your implementation for now.

**Comment by akshayah3** [comment]
Sort of unrelated to this PR but would the implementation for PostgreSQL data source be similar to this? Or does this library already supports PostgreSQL? Sorry as i couldn't find anything on these lines

**Comment by qmnonic** [comment]
Bump.

**Comment by dholbach** [comment]
Just a quick PSA from me: 
1. we're hanging out in [#grafanalib on Slack](https://weave-community.slack.com/archives/grafanalib)
1. we're planning a contributors meeting soon: here's the [link to the doodle](https://doodle.com/poll/hgsp9wmuff7m9bi7) to find a good time - be sure to pick your timezone before submitting ([preliminary agenda](https://docs.google.com/document/d/1JxrSszyPHYhNbJDWYZehRKv6AO4U-zIBhuNmYQVOIHo/edit))

We'd love to see you there.

**Comment by m-d-johnson** [comment]
Was there any progress on this? I'm looking at generating some stuff using InfluxDB and it would be really useful. It's either mangling the strings I put in or not putting them in at all.

**Comment by qmnonic** [comment]
My PR works great.  No one here seems to want to approve/merge it.

**Comment by dholbach** [comment]
@qmnonic and everyone else: Sorry for the long wait. Maintenance of grafanalib has slowly been picked up by a small team of folks and we're happy to see people like you contributing!

I personally have little experience with InfluxDB. Do you think you line out some steps on how I could test this?

**Comment by m-d-johnson** [comment]
@qmnonic - it seems those CI tests are failing for the sake of a couple of linter errors, which just want an extra newline to be added in two files. Do you think you could fix those? We'd be in a better place if the CI tests were passing.

@dholbach - thanks! It's great to hear maintenance has been picked up :)

**Comment by dholbach** [comment]
> @dholbach - thanks! It's great to hear maintenance has been picked up :)

We're off to a good start, but we're actually looking for more folks who are interested in helping out. We're [on Slack](https://weave-community.slack.com/archives/grafanalib) and have [monthly meetings](https://docs.google.com/document/d/1JxrSszyPHYhNbJDWYZehRKv6AO4U-zIBhuNmYQVOIHo/edit) if you'd like to know more. :-)

**Review by matthewmrichter — APPROVED** [review]

**Pull request merged**
