### PR TITLE
Remove gfdatasource from the repo

### LINKED ISSUE #76: Push gfdatasource to docker hub as well as quay.io
The [blog post](https://www.weave.works/blog/grafana-dashboards-as-code/) refers to weaveworks/gfdatasource:latest, but we aren't pushing there any more. We should keep pushing there because:

- it keeps the blog post relevant
- people look for things on DockerHub

CC @errordeveloper

### LINKED ISSUE #94: Update docs re data source for new grafana releases
ISTR new grafana releases have better ways of specifying the data source. We should find those and refer to them in the docs, promoting gfdatasource only for older versions.

### LINKED ISSUE #140: Don't use build-tools
grafanalib doesn't benefit much from using Weaveworks' common build-tools, as it doesn't need to generate images (now that gfdatasource is obsolete), and it is not built with Go.  We should just stop using it.

### PR DESCRIPTION
**Pull request by bboreham**
As noted in #94, `gfdatasource` is unnecessary as the feature is built in to Grafana.

Since we don't need any tools except Python now, use the Circle CI Python image instead of a Go image.

Fixes #94 
Fixes #140 
Fixes #76

### CODE REVIEW

**Comment by dholbach** [comment]
This looks nice and clean and things continue to work. A couple of questions:

- a search on Github shows that a couple of folks use the image - do we need to do anything?
- as #140 gets closed, can we drop the /tools directory?
- will we go with 0.6.0 or will we aim for a 1.0 release (note there's a milestone with a few issues - not sure if we want to fix those all)

@matthewmrichter Your input would be welcome here too.

**Comment by bboreham** [comment]
I think the mentions elsewhere on GitHub stem from using the image in a test for the FluxCD project.  That test was removed some months ago.

The script `tools/image-tag` is called from the Makefile.  Otherwise I think we can drop it.

I think 0.6 is better, since there are other breaking changes up for debate.

**Comment by matthewmrichter** [comment]
I do agree that there are some breaking changes on the horizon that might merit a major release number bump. #172, etc (or equivalent functionality)

**Comment by dholbach** [comment]
Re: #140 - are we going to drop `/tools` in this PR now?

**Pull request merged**
