### PR TITLE
Add description attribute to Dashboard.

### PR DESCRIPTION
**Pull request by franzs**
## What does this do?
Add description attribute to Dashboard. Thus description field can be filled for dasboards.

## Why is it a good idea?
Descriptions (and comments) are always a good idea. ;-) Other classes also have a description field in grafanalib.

### CODE REVIEW

**Comment by dholbach** [comment]
Just a quick PSA from me: 
1. we're hanging out in [#grafanalib on Slack](https://weave-community.slack.com/archives/grafanalib)
1. we're planning a contributors meeting soon: here's the [link to the doodle](https://doodle.com/poll/hgsp9wmuff7m9bi7) to find a good time - be sure to pick your timezone before submitting ([preliminary agenda](https://docs.google.com/document/d/1JxrSszyPHYhNbJDWYZehRKv6AO4U-zIBhuNmYQVOIHo/edit))

We'd love to see you there.

**Comment by dholbach** [comment]
Can you rebase?

**Comment by franzs** [comment]
Sure. Sorry for the delay.

**Comment by dholbach** [comment]
No worries - thanks for looking into this!

**Pull request merged**
