### PR TITLE
Added Grafana 8.x new Alert Rule

### PR DESCRIPTION
**Pull request by vcandeau**
## What does this do?
Create Alert Rule for the new grafana 8.x alerting system

## Why is it a good idea?
Create Panel with thresold and associate their Alert after with almost the same information

## Context
-

## Questions
-

### CODE REVIEW

**Comment by JamesGibo** [comment]
Thanks for the PR, it look good, but i have a couple of bits of feedback:
* Don't worry about the failed doc tests - I need to fix that
* Please could you fix the missing  variables you have defined as defaults
* Please could you add a description of each of the parameters supported by the new `AlertRuler` class you created (look at the other classes for examples)?
* Please could you also add a simple unit test of the class in https://github.com/weaveworks/grafanalib/blob/main/grafanalib/tests/test_core.py

**Comment by vcandeau** [comment]
@JamesGibo  I have made the asked change ;)

**Comment by JamesGibo** [comment]
@vcandeau thanks for addressing those comments, please could you fix the error in the python tests?
You can test locally using `make all`

**Comment by vcandeau** [comment]
@JamesGibo Fix

**Comment by vcandeau** [comment]
@JamesGibo should be fix now ( and test locally )

**Comment by vcandeau** [comment]
Fix

**Comment by JamesGibo** [comment]
I have not used the new alerting in grafana yet, but after looking at your code, so we need to make the `AlertRuler` class support multiple rules. At the moment it just supports a single rule.
Could this be split into a separate class?

**Comment by vcandeau** [comment]
@JamesGibo I think so, could you merge this first class for now and i begin to work on a new version that bring separate class to manage rules ?

**Comment by OscarVanL** [comment]
I just spent several hours today trying to figure out why I could not create Alerts using grafanalib using the existing types. I eagerly await this MR being merged! Great work so far!

**Comment by OscarVanL** [comment]
Thanks for the work starting this off @vcandeau , I've just created a PR that fleshes out this feature more, I'd love your feedback.

**Comment by JamesGibo** [comment]
@vcandeau thanks for your contribution, i have now merged #523 which builds on this PR, so will close this PR.

**Pull request closed without merging**
