### PR TITLE
Repair tests

### PR DESCRIPTION
**Pull request by uritau**
## What does this do?
This PR makes some small changes in order to pass the test suite.

## Why is it a good idea?
It doesn't change "anything" only some deprecation/errors during tests.

 I think that it's clear to have different changes in splited commits to review the PR so Before merge it will be necessary to squash all the commits.

### CODE REVIEW

**Comment by bboreham** [comment]
The last CI build passed all tests, so please can you explain why they need fixing.

(Assume I know nothing about Python - see #160)

**Comment by bboreham** [comment]
OK I see your first commit fixed the same thing as #180.  
The rest are fixing warnings, maybe?

**Comment by bboreham** [comment]
Thanks!

**Comment by dholbach** [comment]
@uritau Can you take a look at https://github.com/weaveworks/grafanalib/pull/197 maybe? Looks like the change in `README.rst` broke the example?

**Pull request merged**
